tasks:
  set_extended_memory_limit: false
  notarize: false
  clean: false
  patch: false
  overwrite_keystore: false

patch:
  path: "renpy-patches"

overwrite_keystore:
  keystore: "<my b64-encoded keystore>"

build:
  pc: true
  mac: true
  android: true

renutil:
  version: "latest"
  registry: "cache"

notarize:
  apple_id: fill-this-in
  password: fill-this-in
  identity: fill-this-in
  bundle: com.my-organization.my-game
  altool_extra:
